# Generated by Django 5.0.7 on 2024-09-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
